apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "telestaid.name" . }}
  labels:
  {{- include "telestaid.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.capacity }}
