apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "litecoind.name" . }}
  labels:
  {{- include "litecoind.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.capacity }}
